### PR TITLE
Added multiple filter pages for Android Auto and AAOS

### PR DESCRIPTION
**Pull request by Ixam97**
I've added multiple pages for filters in Android Auto and AAOS. 

The number of rows on a screen is limited to at least six. Since there are 11 filters, not all could be used.
To be able to to this all multiple choice filters have been moved to the first page because thex require an additional layer which the second page already occupies. 

Also added a limit to how many filter profiles can be saved depending on the limit of rows. To do: differ beweteen Android Auto and AAOS since Android Auto is part of the phone app and should not have a limit. I have no emulator set up to test the Android Auto version but the limit is only implemented in the UI for cars. So it should only not be possible to save from the car UI, but the phone app should not have such a restriction.

### CODE REVIEW

**Comment by johan12345** [comment]
Thanks a lot! I pushed some more commits with some cleanup and a slightly different approach, using the `DummyReturnScreen` to work around the template refresh limitations. This way, the order of filters does not need to be changed.

This same approach would in principle allow us to make the `FilterScreen` have multiple pages as well (even an arbitrary number of pages). Then we wouldn't need the extra logic for preventing the user from saving extra filter profiles.

However, as the action buttons on the `FilterScreen` are already occupied by the edit and delete buttons, we would probably need to implement this using extra list items at the top and/or bottom (for "next" and "previous"). Do you think that makes sense? If we do that, we should then probably change the `EditFiltersScreen` to use the same layout as well.

**Comment by Ixam97** [comment]
I have to say you solution looks quite a bit more elegant (which is to be expected looking at my kotlin/android experience 😅 ). Seems to be working as intended on my side.

One thing I noticed: (At least on the emulator) it takes some loading time to switch between the pages (not allways weirdly), which is caused by the dummyScreen. When I thinkered with my approach I noticed this too, but it had an other cause. This behaviour was gone when Page 1 and 2 used the same FilterViewModel and not their own instances of that (which was in my case necessary to retain changes when switching pages). Do you think there is a way arround this? Since my car only arrives in a few weeks I can't test out if this loading is too short to be noticed on real hardware, but I will do that when it's here.

Also, just out of curiosity: I tried to just use invalidate() in the ClickListener. This works for going to page 1, but not going back to page 0: ``Remote getTemplate onSuccess call failed``. Do you know why this works one way but not the other?

> However, as the action buttons on the FilterScreen are already occupied by the edit and delete buttons, we would probably need to implement this using extra list items at the top and/or bottom (for "next" and "previous"). Do you think that makes sense? If we do that, we should then probably change the EditFiltersScreen to use the same layout as well.

I think that would be a nice addition to make the the different versions more similar in their functionality in the long run.

Is it possible to mix different kinds of rows in the same list so that "next" and "preivous" dont have to have a radio button?

**Comment by johan12345** [comment]
> it takes some loading time to switch between the pages (not allways weirdly), which is caused by the dummyScreen
> Do you think there is a way arround this?

I don't know how fast this is on real hardware, but I think there is no good way around this - the EditFiltersScreen is not recreated in this case, it should be the same instance that is kept on the stack while the dummy screen briefly takes over. I would rather not directly ask the Car App Library team about this workaround for implementing lists of unlimited length, as it is probably not intended behavior 😉 . I hope at some point there will be a better solution (e.g. like for media apps on Android Auto, which can show arbitrarily long lists while parked and force you to wait for a couple seconds when scrolling for too long while driving).

> Also, just out of curiosity: I tried to just use invalidate() in the ClickListener. This works for going to page 1, but not going back to page 0: Remote getTemplate onSuccess call failed. Do you know why this works one way but not the other?

That's because each `invalidate()` call gets counted as a new level of navigation hierarchy (at least in most cases, loading screens or some minor updates are exempt from this).

> Is it possible to mix different kinds of rows in the same list so that "next" and "preivous" dont have to have a radio button?

Ah. Hm... that actually doesn't seem to be possible 😞  Then we'd have to do the flipping through pages with an `ActionStrip` action here in the `FilterScreen` and move the *delete* action back to the `EditFilterScreen` (where we can use rows to link to the next and previous page). Then it's inconsistent again... but I guess it's the best we can do, right?

**Comment by johan12345** [comment]
I just pushed the version of the `EditFiltersScreen` with rows to link to next and previous page, if you want to try it out.

**Comment by Ixam97** [comment]
> I don't know how fast this is on real hardware, but I think there is no good way around this - the EditFiltersScreen is not recreated in this case, it should be the same instance that is kept on the stack while the dummy screen briefly takes over.

Yeah, I figured that out, too. Just for testing I changed the Loading... string to "Dummy" and removed the loading. So it is the dummy screen that is seen. Since it does not happen always I would guess those are emulator hickups. Loading times for a simple 5 char string seems a bit weird, though.

> But I guess it's the best we can do, right?

Only other way I could think of would be the way I suggested earlyer with the list of profiles being on a separate layer, adding an additional tap to select a profile (from the first page at least). On the other hand it would free up space for possible future additions.

**Comment by johan12345** [comment]
>> Is it possible to mix different kinds of rows in the same list so that "next" and "preivous" dont have to have a radio button?
>
> Ah. Hm... that actually doesn't seem to be possible 😞 Then we'd have to do the flipping through pages with an ActionStrip action here in the FilterScreen and move the delete action back to the EditFiltersScreen (where we can use rows to link to the next and previous page).

I tried to implement this, but it turns out that it's also not possible to have a screen with radio buttons where no item is selected. So now I replaced the radio buttons with custom icons, similar to how I solved it in the `MultipleChoiceFilterScreen`. And in that case we can also use the same concept with extra rows for the forward/back buttons for consistency. What do you think?

**Comment by Ixam97** [comment]
> What do you think?

I think thats a great idea. Seems to be working fine 👍 
But I noticed a bug: If you modify a profile and go back without saving the new "Modified filter" row pushes off the next page button. Only after going back to the map screen that button reappears. Also "Modified filter" appears on all pages. Is this intended?

I've made a small adjustment and replaced "Next" and "Back" with "Page x" to make it more obvous that especially the back button has a different function than the back button in the Action Strip.

**Comment by johan12345** [comment]
> I've made a small adjustment and replaced "Next" and "Back" with "Page x" to make it more obvous that especially the back button has a different function than the back button in the Action Strip.

Yeah, good idea. I've updated the German strings as well now.

> But I noticed a bug: If you modify a profile and go back without saving the new "Modified filter" row pushes off the next page button. Only after going back to the map screen that button reappears. Also "Modified filter" appears on all pages. Is this intended?

Ah sorry, that was not intended. Should be fixed now 🙂

**Comment by Ixam97** [comment]
Seems to be working well 👍 

I think this solves the row limitations quite nicely. Thanks for the quick implementation!

**Pull request merged**
