### PR TITLE
Implement fronyx prediction API

### PR DESCRIPTION
**Pull request by johan12345**
[fronyx](https://fronyx.io/), who are building short-term predictions of EV charger availability, approached me and offered to make this data available for EVMap.

This will initially only be available for DC chargers in Germany, can be expanded to other countries in the future.

To do:
- [x] Discuss final UI with fronyx
- [x] Add labels to graph
- [x] Only load data for supported chargers (CCS and CHAdeMO located in Germany)
- [x] Set y-limits of graph based on total number of supported plugs
- [x] Add note that predictions are only for DC plugs so far
- [x] If connector filter is set, only show prediction for filtered connectors
- [x] Add info button which links to description of the data (e.g., FAQ page)
- [x] Add small fronyx logo
- [x] Move x axis labels to the center of the bars
- [x] Add fronyx to data protection statement (#240)
- [x] Rework tooltip implementation so that the whole text is shown - maybe replace it with a dialog
- [x] Add option to disable predictions

### CODE REVIEW

**Comment by Altonss** [comment]
> [fronyx](https://fronyx.io/), who are building short-term predictions of EV charger ability approached me and offered to make this data available for EVMap.

This looks interesting, but what kind of predictions does fronyx provide exactly? I haven't really understood by looking at their website. What would be displayed inside of EVMap for example? Charger available in 15 minutes?

**Comment by johan12345** [comment]
In the current version, they basically predict the status (available or unavailable) of each connector in 15 minute increments for the next couple of hours. In the UI I would probably aggregate that information over all connectors of the same type at a site (e.g. 4 of 6 connectors available).

Of course those predictions will never be 100% accurate, but at least for the very near future it should not be too difficult to predict.

**Comment by Altonss** [comment]
> In the current version, they basically predict the status (available or unavailable) of each connector in 15 minute increments for the next couple of hours. In the UI I would probably aggregate that information over all connectors of the same type at a site (e.g. 4 of 6 connectors available).
> 
> Of course those predictions will never be 100% accurate, but at least for the very near future it should not be too difficult to predict.

It would be in for of a histogram?

**Comment by johan12345** [comment]
Probably yes, at least that's my current idea. But I will discuss with them again if they have other suggestions.

**Pull request merged**
